FROM centos:7

RUN yum install -y https://repo.percona.com/yum/percona-release-latest.noarch.rpm \
    && yum-config-manager --save --setopt=percona-release-noarch.skip_if_unavailable=false \
    && yum update -y \
    && yum install -y percona-xtrabackup 
